### ISSUE TITLE
Theme doesn't build/render

### ISSUE THREAD

**Issue by truedat101** [IoTone/hugo-gwatt-japan-biz-theme#2]
After pull request, the theme won't render.

Run: hugo server

partial error output:

ERROR render of "taxonomy" failed: hugo-spectralk-japan-biz-theme/themes/japan-biz/layouts/_default/baseof.html:11:9": execute of template failed: template: _default/list.html:11:9: executing "_default/list.html" at <partial "header.html" .>: error calling partial: "hugo-spectralk-japan-biz-theme/themes/japan-biz/layouts/partials/header.html:1:3":

hugo version: hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/arm64 BuildDate=2023-12-08T08:47:45Z VendorInfo=brew

**Comment by truedat101** [comment]
@garethwatt please have a look.  Update your fork.  See if you can reproduce.  If you cannot, please publish what version of hugo you are using.  You may need to clone this repository directly and try to reproduce.

**Comment by garethwatt** [comment]
Can't replicate on hugo v0.135.0

hugo server     
Watching for changes in /Users/gareth/Downloads/hugo-spectralk-japan-biz-theme-main/{archetypes,content,themes}
Watching for config changes in /Users/gareth/Downloads/hugo-spectralk-japan-biz-theme-main/hugo.toml
Start building sites … 
hugo v0.135.0+extended darwin/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=brew


                   | EN | JA  
-------------------+----+-----
  Pages            | 19 | 18  
  Paginator pages  |  0 |  0  
  Non-page files   |  1 |  1  
  Static files     |  1 |  1  
  Processed images |  0 |  0  
  Aliases          |  1 |  0  
  Cleaned          |  0 |  0  

Built in 19 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop
^C%                                                                                                                                ➜  hugo-spectralk-japan-biz-theme-main hugo            
Start building sites … 
hugo v0.135.0+extended darwin/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=brew


                   | EN | JA  
-------------------+----+-----
  Pages            | 19 | 18  
  Paginator pages  |  0 |  0  
  Non-page files   |  1 |  1  
  Static files     |  1 |  1  
  Processed images |  0 |  0  
  Aliases          |  1 |  0  
  Cleaned          |  0 |  0  

Total in 25 ms

**Comment by truedat101** [comment]
Let me update brew.  Please clarify the origins of this theme.  If it was not a fork of the other theme mentioned, we can and should cleanup the README accordingly.  The original plan was to use the other theme as a starting point and not from scratch. It doesn't matter though at this point.

**Comment by truedat101** [comment]
Resolved with v0.135.0.
